### ISSUE TITLE
Security Group for "Nodes" are not updated -> health checks fail

### ISSUE THREAD

**Issue by Deshke** [coreos/alb-ingress-controller#100]
ingress with 

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "web-frontend"
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-123,subnet-456,subnet-789
    alb.ingress.kubernetes.io/security-groups: sg-147
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    # alb.ingress.kubernetes.io/certificate-arn:  
    alb.ingress.kubernetes.io/healthcheck-path: /
    # alb.ingress.kubernetes.io/listen-ports: default 80
    alb.ingress.kubernetes.io/successCodes: "200-399"
  labels:
    group: service-frontend
spec:
  rules:
  - host: frontend-dev.domain.tld
    http:
      paths:
      - path: /
        backend:
          serviceName: "app-web-app01"
          servicePort: 80
```
does not update the needed configuration for the ec2 instance itself - so all health checks fail and the alb responses with 50x. After manually adding the `sg-147` to the `node` sg, it works 

running ` quay.io/coreos/alb-ingress-controller:latest` (`https://quay.io/repository/coreos/alb-ingress-controller/image/a8e07e417d7fe3381948414c3c36102a69518f5553cc3f76ac2a06f16147e8b8`
