### ISSUE TITLE
alb-ingress-controller not creating route 53 dns entry

### ISSUE THREAD

**Issue by hsuchan** [coreos/alb-ingress-controller#105]
Issue: when deploying helm configs in tectonic using alb-ingress-controller, the route 53 dns entry is not created.

Here is my ingress.yaml file:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{.Chart.Name}}-{{.Values.env}}
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/healthcheck-path: {{.Values.healthcheck}}
    alb.ingress.kubernetes.io/subnets: {{.Values.tier}}-1.{{.Values.vpc}},{{.Values.tier}}-2.{{.Values.vpc}},{{.Values.tier}}-3.{{.Values.vpc}}
    alb.ingress.kubernetes.io/security-groups: {{.Values.vpc}}.onprem,{{.Values.vpc}}.{{.Values.tier}}
    alb.ingress.kubernetes.io/tags: Environment={{.Values.env}},ProductCode={{.Values.productCode}},InventoryCode={{.Values.inventorycode}}
spec:
  rules:
  - host: {{.Values.queryFQDN}}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{.Chart.Name}}-{{.Values.env}}
          servicePort: 9000
```

Manual steps to force a dns update (as workaround):

- Update dns host (i.e. by adding a character to the hostname)
- Perform "helm upgrade"
- Change dns host back to its original value
- Perform "helm upgrade" again

This somehow triggers a dns update, and the route 53 dns entry is finally created.
