### ISSUE TITLE
Tagging of ALBs does not work.

### ISSUE THREAD

**Issue by jescarri** [coreos/alb-ingress-controller#121]
Specifying the ALB tags via `alb.ingress.kubernetes.io/tags` does not work, the controller create the ALB without the extra tags.

Alb Ingress version: latest
Example manifest:
````
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: test-ingress
  namespace: default
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /graph
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/security-groups: 'dev.access'
    alb.ingress.kubernetes.io/subnets: 'test-subnets'
    alb.ingress.kubernetes.io/tags: >-
      Environment=foo=bar
spec:
  rules:
    - host: test.domain.com
      http:
        paths:
          - path: /graph
            backend:
              serviceName: prometheus
              servicePort: 9090
````
