### ISSUE TITLE
multiple http ports don't work

### ISSUE THREAD

**Issue by jwhitcraft** [coreos/alb-ingress-controller#128]
Hello, i'm trying to define multiple http ports to listen on, but i'm only ever seeing port 80 in alb

here is my ingress

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "nexus-alb"
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/subnets: subnet-one,subnet-two,subnet-three
    alb.ingress.kubernetes.io/security-groups: "redacted"
    alb.ingress.kubernetes.io/certificate-arn: "redacted"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 8181, "HTTP": 80, "HTTPS": 443}]'
    kubernetes.io/ingress.class: "alb"
  labels:
    app: nexus
spec:
  rules:
  - host: "cache.myhost.io"
    http:
      paths:
      - path: /
        backend:
          serviceName: "nodeport-nexus"
          servicePort: 8081
```

Here is the alb listeners,  it's missing port 8181, 

<img width="1165" alt="screenshot 2017-06-29 11 06 54" src="https://user-images.githubusercontent.com/26738/27694815-386e68fe-5cbb-11e7-92da-41fbca84ddb6.png">

from the code it looks like multiple ports are supported, but it doesn't seem to be working.
