### ISSUE TITLE
Are multiple hosts allowed?

### ISSUE THREAD

**Issue by olitheolix** [coreos/alb-ingress-controller#200]
I would like to configure multiple hosts in the Ingress file. I have tried this
```
  - host: foo.net
    http:
      paths:
      - path: /
        backend:
          serviceName: "service-foo"
          servicePort: 80
  - host: bar.net
    http:
      paths:
      - path: /
        backend:
          serviceName: "service-bar"
          servicePort: 80
```
and it deploys correctly (ie creates two LBs, two target groups, two Route53 entries).

However, the second Target Group receives only default parameters (eg `alb.ingress.kubernetes.io/healthcheck-path` will be applied to the first TG but not the second).

Finally, once I destroy the Ingress resource, the controller segfaults
`E0911 23:30:16.249631       1 runtime.go:66] Observed a panic: "slice bounds out of range" (runtime error: slice bounds out of range)`

Is the controller supposed to support multiple hosts, or am I asking too much?
