### ISSUE TITLE
Controller invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by tomhughesnice** [coreos/alb-ingress-controller#206]
I am currently using image quay.io/coreos/alb-ingress-controller:0.8.

I have setup an ingress controller pointing to service that was working fine. But whenever I deploy a change to that service the load balancer will only return an 502 Bad gateway indefinitely.  

Looking at the logs it appears the Controller has crashed. Here are the logs

`I0914 13:26:43.357158       1 controller.go:1183] starting Ingress controller
I0914 13:26:43.358839       1 leaderelection.go:203] attempting to acquire leader lease...
I0914 13:26:43.377445       1 event.go:217] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"fieldmargin-dev", Name:"edge-service-ingress", UID:"2a6e101e-97cd-11e7-978d-02fd8571b5e2", APIVersion:"extensions", ResourceVersion:"4139217", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress fieldmargin-dev/edge-service-ingress
I0914 13:26:43.408652       1 leaderelection.go:213] successfully acquired lease default/ingress-controller-leader-alb
W0914 13:26:44.358781       1 backend_ssl.go:42] deferring sync till endpoints controller has synced
W0914 13:26:44.377588       1 queue.go:88] requeuing fieldmargin-dev/edge-service-ingress, err deferring sync till endpoints controller has synced
I0914 13:26:46.010121       1 log.go:48] [ALB-INGRESS] [fieldmargin-dev-edge-service-ingress] [INFO]: Start TargetGroup deletion.
I0914 13:28:27.604787       1 log.go:48] [ALB-INGRESS] [fieldmargin-dev-edge-service-ingress] [INFO]: Completed TargetGroup deletion.
I0914 13:28:27.604809       1 log.go:48] [ALB-INGRESS] [fieldmargin-dev-edge-service-ingress] [INFO]: Start TargetGroup creation.
I0914 13:28:27.945443       1 log.go:48] [ALB-INGRESS] [fieldmargin-dev-edge-service-ingress] [INFO]: Succeeded TargetGroup creation. ARN: arn:aws:elasticloadbalancing:eu-west-1:107642239582:targetgroup/k8s-30902-HTTP-bd39b7b/f121d828571572c0 | Name: k8s-30902-HTTP-bd39b7b.
I0914 13:28:27.945504       1 log.go:48] [ALB-INGRESS] [fieldmargin-dev-edge-service-ingress] [INFO]: Start Rule creation.
E0914 13:28:27.945623       1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/lib/go/src/runtime/asm_amd64.s:514
/usr/lib/go/src/runtime/panic.go:489
/usr/lib/go/src/runtime/panic.go:63
/usr/lib/go/src/runtime/signal_unix.go:290
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/rule.go:106
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/rule.go:78
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/rules.go:14
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/listeners.go:32
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/loadbalancers.go:42
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/ingress.go:356
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/controller.go:112
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:413
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:164
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:87
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:97
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:98
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:52
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49
/usr/lib/go/src/runtime/asm_amd64.s:2197
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x14935d9]
 goroutine 105 [running]:
github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x126`

**Comment by tomhughesnice** [comment]
Ok so quay.io/coreos/alb-ingress-controller:0.8 is 3 months old. Should i use latest? 

Do you document your releases anywhere? At the moment I don't know what version I should be using.

**Comment by joshrosso** [comment]
@tomhughesnice : apologies for the confusion, we've been a bit all over the place but are getting close to stabilizing as we move toward 1.0 and get a consistent release stream setup.

See https://github.com/coreos/alb-ingress-controller/pull/197.

I'm trying to tackle all seg fault / panic issues now. Are you willing to try this scenario with `b30d8d28` and let me know if the issue persists?

**Comment by tomhughesnice** [comment]
I just deployed b30d8d28 and redeployed my service. The instant the deployment started the load balancer started returning 502 errors.

The logs didnt seem to indicate any error. 

I0914 15:08:17.137546       1 leaderelection.go:184] successfully acquired lease default/ingress-controller-leader-alb
I0914 15:08:17.137574       1 status.go:193] new leader elected: intentional-sasquatch-alb-ingress-controller-helm-controllt940k
I0914 15:09:59.157196       1 controller.go:477] backend reload required
I0914 15:09:59.157402       1 targetgroup.go:145] [ALB-INGRESS] [fieldmargin-dev/edge-service-ingress] [INFO]: Start TargetGroup deletion.
I0914 15:11:40.230229       1 targetgroup.go:150] [ALB-INGRESS] [fieldmargin-dev/edge-service-ingress] [INFO]: Completed TargetGroup deletion.
I0914 15:11:40.230255       1 targetgroup.go:154] [ALB-INGRESS] [fieldmargin-dev/edge-service-ingress] [INFO]: Start TargetGroup creation.
I0914 15:11:40.698224       1 targetgroup.go:161] [ALB-INGRESS] [fieldmargin-dev/edge-service-ingress] [INFO]: Succeeded TargetGroup creation. ARN: arn:aws:elasticloadbalancing:eu-west-1:107642239582:targetgroup/k8s-30924-HTTP-9cd36a3/b8a0a6c8bf27d09a | Name: k8s-30924-HTTP-9cd36a3.
I0914 15:11:40.698299       1 controller.go:486] ingress backend successfully reloaded...
I0914 15:11:40.698505       1 controller.go:477] backend reload required
I0914 15:11:40.698730       1 controller.go:486] ingress backend successfully reloaded...

I do blue/green deployments so there is always a pod available to serve traffic. Now the deployment is completed I still only receive 502 responses.

My Ingress is the following if that helps.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: edge-service-ingress
  namespace: fieldmargin-dev
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/security-groups: sg-bb67edc3,sg-5666ec2e,sg-bc67edc4
    alb.ingress.kubernetes.io/subnets: subnet-6b4f8f30,subnet-63b13d2a,subnet-6931b50e
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-1:107642239582:certificate/bd769b07-cabc-44d6-9657-e6a87c71865b
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/alb: alb-dev-1
  labels:
    app: edge-service-ingress
spec:
  rules:
  - host: rest-dev-kubernetes.fieldmargin.com
    http:
      paths:
      - path: /
        backend:
          serviceName: edge-service-boot
          servicePort: 8080
```
