### ISSUE TITLE
changes does not update the the target group in aws

### ISSUE THREAD

**Issue by yawboateng** [coreos/alb-ingress-controller#231]
I  had an ingress. the alb with rules was success created in aws:
```
- host: sub.example.com
    http:
      paths:
      ...
      ...
  - host: www.example.com
    http:
      paths:
      - backend:
          serviceName: ui
          servicePort: 80
        path: /*
      - backend:
          serviceName: requests
          servicePort: 80
        path: /api/v1/ben*
```

however, when i flipped the requests rule with the UI, the alb header and path rules were update in aws, but the target groups were still pointing to the old ones (so ui target group was set to requests and vise versa)

```
  - host: www.example.com
    http:
      paths:
      - backend:
          serviceName: requests
          servicePort: 80
        path: /api/v1/ben*
      - backend:
          serviceName: ui
          servicePort: 80
        path: /*

```

**Comment by joshrosso** [comment]
@yawboateng - what version of the controller are you using?

**Comment by yawboateng** [comment]
Hi @joshrosso running `93578098`

**Comment by joshrosso** [comment]
Thanks @yawboateng 

Would you be willing to try this modification with `1.0-alpha.3` and let me know if the issue persists?

Note these new alpha version no longer sync with route53 natively. But you can use external-dns to fill that gap. Docs https://github.com/coreos/alb-ingress-controller/blob/master/docs/setup.md#external-dns-deployment

**Comment by whithajess** [comment]
@joshrosso Can confirm the issue exists on `1.0-alpha.3` I have just done a `rolling-update` using `kops` and all my target groups left with no registered targets. 

Logs:

```
I1008 21:37:39.724586       1 launch.go:295] Running in Kubernetes Cluster version v1.7 (v1.7.3) - git (clean) commit 2c2fe6e8278a5db2d15a013987b53968c743f2a1 - platform linux/amd64
I1008 21:37:39.727467       1 launch.go:134] validated kube-system/default-http-backend as the default backend
I1008 21:37:39.734057       1 albingresses.go:85] [ALB-INGRESS] [ingresses] [INFO]: Build up list of existing ingresses
```

**Comment by yawboateng** [comment]
confirmed it to be the same and also I noticed:

```
- host: sub.example.com
    http:
      paths:
      ...
      ...
  - host: www.example.com
    http:
      paths:
      - backend:
          serviceName: ui
          servicePort: 80
        path: /*
      - backend:
          serviceName: requests
          servicePort: 80
        path: /api/v1/ben*
```
when i add a new rule under sub.example.com, it points it to the last target group of the last rule of www.example.com and then also points those two rules under www.example.com to the same target groups
