### ISSUE TITLE
Updates to single listener port are not reconciled correctly.

### ISSUE THREAD

**Issue by joshrosso** [coreos/alb-ingress-controller#241]
When an ingress resource contains a single listener.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":8080}]'
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/successCodes: "200"
    alb.ingress.kubernetes.io/tags: <REDACTED>
    kubernetes.io/ingress.class: alb
  labels:
    app: <REDACTED>
  name: <REDACTED>
  namespace: <REDACTED>
spec:
  rules:
  - host: <REDACTED>
    http:
      paths:
      - backend:
          serviceName: <REDACTED>
          servicePort: 80
        path: /
```

Altering the `listen-ports` annotation will cause for the new port to be added but the old port to remain.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/successCodes: "200"
    alb.ingress.kubernetes.io/tags: <REDACTED>
    kubernetes.io/ingress.class: alb
  labels:
    app: <REDACTED>
  name: <REDACTED>
  namespace: <REDACTED>
spec:
  rules:
  - host: <REDACTED>
    http:
      paths:
      - backend:
          serviceName: <REDACTED>
          servicePort: 80
        path: /
```

As seen in this view of the console.

![image](https://user-images.githubusercontent.com/6200057/31568128-9d2c29c4-b027-11e7-84bc-c2cbc7265843.png)
