### ISSUE TITLE
alb controller need the privilege to create configmap

### ISSUE THREAD

**Issue by andromedarabbit** [coreos/alb-ingress-controller#245]
Encountered the error `E1017 01:59:50.155960       1 leaderelection.go:228] error initially creating leader election record: User "system:serviceaccount:kube-system:alb-ingress-controller" cannot create configmaps in the namespace "kube-system". (post configmaps)` with [the sample clusterrole description](https://github.com/coreos/alb-ingress-controller/blob/master/alb-ingress-controller-helm/templates/clusterrole.yaml):

``` yaml
rules:
  - apiGroups:
      - ""
      - extensions
    resources:
      - endpoints
      - events
      - ingresses
      - ingresses/status
    verbs:
      - create
      - get
      - list
      - update
      - watch
  - apiGroups:
      - ""
      - extensions
    resources:
      - configmaps
      - nodes
      - pods
      - secrets
      - services
    verbs:
      - get
      - list
      - watch
```

Moving up `configmaps` from the second `apiGroups` to the first one might fix this:

``` yaml
rules:
  - apiGroups:
      - ""
      - extensions
    resources:
      - configmaps
      - endpoints
      - events
      - ingresses
      - ingresses/status
    verbs:
      - create
      - get
      - list
      - update
      - watch
  - apiGroups:
      - ""
      - extensions
    resources:
      - nodes
      - pods
      - secrets
      - services
    verbs:
      - get
      - list
      - watch
```
