### ISSUE TITLE
Listener creation makes extra API call

### ISSUE THREAD

**Issue by joshrosso** [coreos/alb-ingress-controller#25]
## Issue
When constructing multiple listeners (2+ ports) an extra API call for create is made. While the ALB is still setup properly, we'll want to fix this at some point.

## How to Reproduce

Apply a multi-port ingress manifest such as:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echoserver
  namespace: echoserver
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/port: "8080,9000"
    alb.ingress.kubernetes.io/subnets: subnet-63bf6318,subnet-0b20aa62
    alb.ingress.kubernetes.io/security-groups: sg-1f84f776
    alb.ingress.kubernetes.io/tags: Environment=dev1,ProductCode=PRD999,InventoryCode=echo-app
spec:
  rules:
  - host: aaaaaa.josh-test-dns.com
    http:
      paths:
      - path: /
        backend:
          serviceName: echoserver
          servicePort: 80
      - path: /mespecial
        backend:
          serviceName: echoserver2
          servicePort: 80

```

Watch the logs, note the 3 instances of `Start Listener creation`.

```
[ALB-INGRESS] [echoserver-echoserver] [INFO]: Start Listener creation.                                                                                                                         
[ALB-INGRESS] [echoserver-echoserver] [INFO]: Located default rule. Rule: {  Actions: [{      Type: "forward"    }],  IsDefault: true,  Priority: "default"}                                   
[ALB-INGRESS] [echoserver-echoserver] [INFO]: Completed Listener creation. ARN: arn:aws:elasticloadbalancing:us-east-2:432733164488:listener/app/dev1-429acf8d129056e/8349536fda798aee/cbe2f185fc248edc | Port: %!s(int64=8080) | Proto: HTTP.                                                                                                                                                
[ALB-INGRESS] [echoserver-echoserver] [INFO]: Start Listener creation.                                                                                                             
[ALB-INGRESS] [echoserver-echoserver] [INFO]: Located default rule. Rule: {  Actions: [{      Type: "forward"    }],  IsDefault: true,  Priority: "default"}                                   
[ALB-INGRESS] [echoserver-echoserver] [INFO]: Completed Listener creation. ARN: arn:aws:elasticloadbalancing:us-east-2:432733164488:listener/app/dev1-429acf8d129056e/8349536fda798aee/894f4e77e045bd46 | Port: %!s(int64=9000) | Proto: HTTP.                                                                                                                                                
[ALB-INGRESS] [echoserver-echoserver] [INFO]: Start Listener creation.                                                                                                                         
[ALB-INGRESS] [echoserver-echoserver] [INFO]: Completed Listener creation. ARN: arn:aws:elasticloadbalancing:us-east-2:432733164488:listener/app/dev1-429acf8d129056e/8349536fda798aee/cbe2f185fc248edc | Port: %!s(int64=8080) | Proto: HTTP.
```
