### ISSUE TITLE
helm registry clusterrole doesn't allow listing namespaces

### ISSUE THREAD

**Issue by lucasreed** [coreos/alb-ingress-controller#334]
When limiting to a single namespace I see the error:

```
no watchNamespace with name default found: namespaces "default" is forbidden: User "system:serviceaccount:default:alb-controller-alb-ingress-controller" cannot get namespaces in the namespace "default"
```

I fixed this by adding the `namespace` resource to the clusterrole definition that helm registry created.

```
- apiGroups:
  - ""
  - extensions
  resources:
  - nodes
  - pods
  - secrets
  - services
  - namespaces  # Added this.
  verbs:
  - get
  - list
  - watch
```
To Recreate:
I launch the controller like so:

`helm registry install quay.io/coreos/alb-ingress-controller-helm --namespace default --name=alb-controller -f alb-ingress-values.yaml`

The alb-ingress-values.yaml looks like this:

```yaml
# Quay.io doesn't allow container image & application repositories in the same organization
# to share a name. In this case, the image is quay.io/coreos/alb-ingress-controller,
# and the Helm chart is quay.io/coreos/alb-ingress-controller-helm. This variable
# overrides the chart name.
nameOverride: alb-ingress-controller

## AWS region in which this ingress controller will operate
## REQUIRED
#
awsRegion: us-east-1

## Resources created by the ALB Ingress controller will be prefixed with this string
## REQUIRED
#
clusterName: k8s.cluster

controller:
  image:
    repository: quay.io/coreos/alb-ingress-controller
    tag: "1.0-alpha.8"
    pullPolicy: IfNotPresent

  extraEnv: {}
    # AWS_ACCESS_KEY_ID: ""
    # AWS_SECRET_ACCESS_KEY: ""
    # AWS_DEBUG: false
    # AWS_MAX_RETRIES: 20
    # LOG_LEVEL: ""

  nodeSelector: {}
    # node-role.kubernetes.io/node: "true"
    # tier: cs

  podAnnotations: {}
    # iam.amazonaws.com/role: alb-ingress-controller

  podLabels: {}

  # How often (in seconds) to check controller readiness
  readinessProbeInterval: 10

  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 100Mi
    # requests:
    #   cpu: 100m
    #   memory: 100Mi

  service:
    annotations: {}
      # prometheus.io/scrape: "true"

    labels: {}

defaultBackend:
  image:
    repository: gcr.io/google_containers/defaultbackend
    tag: "1.2"
    pullPolicy: IfNotPresent

  nodeSelector: {}
    # node-role.kubernetes.io/node: "true"
    # tier: cs

  podAnnotations: {}
  podLabels: {}
  replicaCount: 1

  resources: {}
    # limits:
    #   cpu: 10m
    #   memory: 20Mi
    # requests:
    #   cpu: 10m
    #   memory: 20Mi

  service:
    annotations: {}
    labels: {}

rbac:
  ## If true, create & use RBAC resources
  ##
  create: true

  ## Ignored if rbac.create is true
  serviceAccountName: default

sidecarContainers: {}
  ## Additional containers to be added to the alb-ingress-controller pod.
  #  - name: my-sidecar
  #    image: nginx:latest

scope:
  ## If provided, the ALB ingress controller will only act on Ingress resources annotated with this class
  ## Ref: https://github.com/coreos/alb-ingress-controller/blob/master/docs/configuration.md#limiting-ingress-class
  #
  ingressClass: alb

  ## If true, the ALB ingress controller will only act on Ingress resources in a single namespace
  ## Default: false; watch all namespaces
  #
  singleNamespace: true

  ## If scope.singleNamespace=true, the ALB ingress controller will only act on Ingress resources in this namespace
  ## Ref: https://github.com/coreos/alb-ingress-controller/blob/master/docs/configuration.md#limiting-namespaces
  ## Default: namespace of the ALB ingress controller
  #
  watchNamespace: "default"

```

Only modified values are:
`clusterName: k8s.cluster # not important`
`controller.image.tag: 1.0-alpha.8`
`scope.singleNamespace: true`
`scope.watchNamespace: "default"`

I'll submit a PR for this, but let me know if this is incorrect and I just deployed something incorrectly.
