### ISSUE TITLE
aws access key id and secret not being recognized

### ISSUE THREAD

**Issue by yawboateng** [coreos/alb-ingress-controller#63]
I created an IAM user and attached the sample policy to it and set the environment variables AWS_ACCESS_KEY_ID/AWS_ACCESS_SECRET_KEY in  my controller deployment, as stated in the [docs](https://github.com/coreos/alb-ingress-controller/blob/master/docs/configuration.md#aws-api-access)

However, the controller seems to be trying to connect to aws using the iam role of the worker nodes instead of the access key id and secret :
```
2017-04-18T02:11:49.885187560Z F0418 02:11:49.884868       1 ingress.go:193] AccessDenied: User: arn:aws:sts::213232:assumed-role/yaw-Cluster-Stack-Workers-IAMRoleWorker-16S6JA1539L6M/i-0f0091907cc651398 is not authorized to perform: elasticloadbalancing:DescribeLoadBalancers
2017-04-18T02:11:49.885211637Z 	status code: 403, request id: 61d1674a-23dc-11e7-a94c-3502ef010ef0
```

works fine when i attach  the sample policy to the worker IAMRole, but will be great if we can just use the access key and secret instead of going through multiple worker roles and attaching to each one

running `quay.io/coreos/alb-ingress-controller:0.8`

**Comment by joshrosso** [comment]
Hi @yawboateng 

It appears our docs were wrong, it should be `AWS_SECRET_ACCESS_KEY` rather than what's documented (`AWS_ACCESS_SECRET_KEY`).

So your env section of the manifest would look something like:
```yaml
        env:                                                                                   
        - name: AWS_REGION                                                                     
          value: us-east-2                                                                     
        - name: AWS_ACCESS_KEY_ID                                                              
          value: VALUE_HERE                                                          
        - name: AWS_SECRET_ACCESS_KEY                                                          
          value: VALUE_HERE  
```

Let me know if this solves your issue and apologies in advanced for the confusion.
