### ISSUE TITLE
controller deletes route53 entries not created by ingress 

### ISSUE THREAD

**Issue by yawboateng** [coreos/alb-ingress-controller#65]
I currently have some route53 dns entries that are created using the classic elb (k8s service Type:LoadBalancer)

However, After deploying this controller, and creating an ingress object (hostname not taken) that uses the controller, I noticed that some of my original dns records (not associated with the ingress object) are automatically being deleted when the controller is creating a route53 entry for the ingress object

**Comment by joshrosso** [comment]
Hi @yawboateng 

Could you give me an example of the pre-existing domain that is being deleted along with the desired domain you put in your ingress object?

**Comment by yawboateng** [comment]
pre-existing domain = scrummaster.infra.sometest.com

ingress:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "elasticsearch"
  namespace: "logging"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-1,subnet-2,subnet-3
    alb.ingress.kubernetes.io/security-groups: sg-1
    alb.ingress.kubernetes.io/certificate-arn: [cert_arn_link]
    kubernetes.io/ingress.class: "alb"

spec:
  rules:
  - host: elasticsearch.infra.sometest.com
    http:
      paths:
      - path: /
        backend:
          serviceName: "elasticsearch"
          servicePort: 9200
```
