### ISSUE TITLE
Duplicated rules

### ISSUE THREAD

**Issue by yawboateng** [coreos/alb-ingress-controller#75]
I have deleted and recreated my ingress object multiple times and I just noticed that in AWS under the alb rules, there are a lot of duplication.

including going into aws and manually deleting all the albs and target groups, but each time the controller recreates the alb, the rules are duplicated

**Comment by joshrosso** [comment]
Hi @yawboateng 

Could you send me a screenshot of what the rule duplication looks like from the AWS UI?

Also, could you provide a sample ingress resource manifest?

**Comment by yawboateng** [comment]
![screen shot 2017-04-25 at 2 05 46 pm](https://cloud.githubusercontent.com/assets/17864529/25400655/3923d78e-29c1-11e7-8836-c4478c9b940b.png)

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cloud-statistics-bot-alb
  namespace: auth
  kubernetes.io/ingress.class: "alb"
spec:
  rules:
  - host: apps.test.com
    http:
      paths:
      - path: /
        backend:
          serviceName: app-bot
          servicePort: 80
      - path: {{ .Values.apiPath }}/internetAddresses/mailServer/*
        backend:
          serviceName: nginx-ingress-controller
          servicePort: 443
      - path: {{ .Values.apiPath }}/user/*
        backend:
          serviceName: nginx-ingress-controller
          servicePort: 443
      - path: {{ .Values.apiPath }}/companies
        backend:
          serviceName: nginx-ingress-controller
          servicePort: 443
      - path: {{ .Values.apiPath }}/users/mailServer/*
        backend:
          serviceName: nginx-ingress-controller
          servicePort: 443
      - path: {{ .Values.apiPath }}/mailServers/intersection
        backend:
          serviceName: nginx-ingress-controller
          servicePort: 443
      - path: {{ .Values.apiPath }}/users/travelerServer/*
        backend:
          serviceName: nginx-ingress-controller
          servicePort: 443
      - path: {{ .Values.apiPath }}/internetAddresses/travelerServer/*
        backend:
          serviceName: nginx-ingress-controller
          servicePort: 443
      - path: {{ .Values.apiPath }}/travelerServers/union
        backend:
          serviceName: nginx-ingress-controller
          servicePort: 443
      - path: /api/v1/oauth2*
        backend:
          serviceName: "oauth2-client"
          servicePort: 80
```
