### ISSUE TITLE
Error: InvalidParameter: 1 validation error(s) found

### ISSUE THREAD

**Issue by yawboateng** [coreos/alb-ingress-controller#81]
is setting a rule like /api/v1/oauth2/sso* not permitted? 

`I0503 19:12:19.611756       1 log.go:62] [ALB-INGRESS] [auth-api-alb-1] [ERROR]: Failed Rule creation. Rule: {  Actions: [{      TargetGroupArn: "arn:aws:elasticloadbalancing:us-east-1",      Type: "forward"    }],  Conditions: [{      Field: "path-pattern",      Values: ["/api/v1/oauth2/sso*"]    }],  IsDefault: false} | Error: InvalidParameter: 1 validation error(s) found.`

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: testing-alb
  namespace: auth
  kubernetes.io/ingress.class: "alb"
spec:
  rules:
  - host: apps.test.com
    http:
      paths:
      - path: /
        backend:
          serviceName: app-bot
          servicePort: 80
      - path: /api/v1/oauth2/sso*
        backend:
          serviceName: "oauth2-client"
          servicePort: 80
```
